//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelorarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class angebot_positionen
    {
        public long id { get; set; }
        public long angebot_id { get; set; }
    
        public virtual angebote angebote { get; set; }
    }
}
