//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelorarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class einstellungen
    {
        public long id { get; set; }
        public decimal standardmehrwertsteuersatz { get; set; }
        public string standardland { get; set; }
        public string speicherortrechnungen { get; set; }
        public string speicherortangebote { get; set; }
        public string firmenname { get; set; }
        public string inhaber { get; set; }
        public string strasse { get; set; }
        public string postleitzahl { get; set; }
        public string ort { get; set; }
        public string land { get; set; }
        public string telefon { get; set; }
        public string telefax { get; set; }
        public string email { get; set; }
        public string webseite { get; set; }
        public string ustidnr { get; set; }
        public string iban { get; set; }
        public string bic { get; set; }
        public string bank { get; set; }
        public string empfaenger { get; set; }
    }
}
