//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelorarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class kunden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kunden()
        {
            this.angebote = new HashSet<angebote>();
            this.rechnungen = new HashSet<rechnungen>();
        }
    
        public long id { get; set; }
        public long kundennummer { get; set; }
        public string anrede { get; set; }
        public string vorname { get; set; }
        public string nachname { get; set; }
        public string firma { get; set; }
        public string strasse { get; set; }
        public string postleitzahl { get; set; }
        public string ort { get; set; }
        public string land { get; set; }
        public string telefon { get; set; }
        public string telefax { get; set; }
        public string mobiltelefon { get; set; }
        public string email { get; set; }
        public string webseite { get; set; }
        public string notizen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<angebote> angebote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rechnungen> rechnungen { get; set; }
    }
}
