//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelorarbeit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<angebot_positionen> angebot_positionen { get; set; }
        public virtual DbSet<angebote> angebote { get; set; }
        public virtual DbSet<einstellungen> einstellungen { get; set; }
        public virtual DbSet<kunden> kunden { get; set; }
        public virtual DbSet<rechnung_positionen> rechnung_positionen { get; set; }
        public virtual DbSet<rechnungen> rechnungen { get; set; }
    }
}
