//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelorarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class rechnungen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rechnungen()
        {
            this.rechnung_positionen = new HashSet<rechnung_positionen>();
        }
    
        public long id { get; set; }
        public long kunde_id { get; set; }
        public long rechnungsnummer { get; set; }
        public string datum { get; set; }
        public string mehrwertsteueranzeige { get; set; }
        public Nullable<long> zahlbartage { get; set; }
        public Nullable<decimal> skontoprozent { get; set; }
        public Nullable<long> skontotage { get; set; }
        public string bemerkung { get; set; }
    
        public virtual kunden kunden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rechnung_positionen> rechnung_positionen { get; set; }
    }
}
