//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bachelorarbeit
{
    using System;
    using System.Collections.Generic;
    
    public partial class rechnung_positionen
    {
        public long id { get; set; }
        public long rechnung_id { get; set; }
        public long ueberschrift { get; set; }
        public Nullable<decimal> menge { get; set; }
        public string einheit { get; set; }
        public string name { get; set; }
        public string beschreibung { get; set; }
        public Nullable<decimal> einzelpreis { get; set; }
        public Nullable<decimal> gesamtpreis { get; set; }
    
        public virtual rechnungen rechnungen { get; set; }
    }
}
